from time import sleep

def ascii_to_bin(text):
    return ' '.join(format(ord(char), '08b') for char in text)

while True:
    print(f"input ascii text here:\n")
    input_text = input("        ")
    binary_output = ascii_to_bin(input_text)
    binary_output = binary_output.replace(" ","")
    binary_output = binary_output.replace("00","uwu ")
    binary_output = binary_output.replace("01","UwU ")
    binary_output = binary_output.replace("00","owo ")
    binary_output = binary_output.replace("11","OwO ")
    binary_output = binary_output.replace("1uwu","uWu")
    binary_output = binary_output.replace("1UwU","UWU")
    binary_output = binary_output.replace("1","oWo")
    binary_output = binary_output.replace("UWU UWU","0wU")
    binary_output = binary_output.replace("UWU UWU UWU","Uw0")
    binary_output = binary_output.replace("UWU UwU","MwM")
    binary_output = binary_output.replace("uwu OwO","IwI")
    binary_output = binary_output.replace("; ; ;","iwi")
    binary_output = binary_output.replace("; ;","ewe")
    binary_output = binary_output.replace("uWu uWu","iWi")
    binary_output = binary_output.replace("UWU uwu","wii")
    binary_output = binary_output.replace("UwU uWu","nWn")
    binary_output = binary_output.replace("UwU uwu",":3")
    binary_output = binary_output.replace(":3 :3","3:")
    binary_output = binary_output.replace("uwu uwu","gay")
    binary_output = binary_output.replace("  "," ")
    binary_output = binary_output.replace("UwU UwU UwU","WuW")
    binary_output = binary_output.replace("UwU OwO WuW","w0w")
    binary_output = binary_output.replace("UwU UwU","wUw")
    binary_output = binary_output.replace("OwO UwU","WOW")
    binary_output = binary_output.replace("UwU OwO","wOw")
    binary_output = binary_output.replace("UwU OwO UwU","wuw")
    binary_output = binary_output.replace("OwO UwU OwO","WUW")
    binary_output = binary_output.replace("UWU UWU",":33")
    binary_output = binary_output.replace("WOW WOW","33:") 
    binary_output = binary_output.replace("WOW WOW","33:") 
    binary_output = binary_output.replace("uWu uwu","U") 
    binary_output = binary_output.replace("uwu uWu","u") 
    binary_output = binary_output.replace("IwI IwI","I")
    binary_output = binary_output.replace("uWu uwu","w")
    binary_output = binary_output.replace("UwU UWU","W")
    print(f"\n\n\n\nEnCoded Form:\n\n", binary_output, f"\n\n\n")